apiVersion: compute.cloudfusion.com/alphav1
kind: EC2Instance
metadata:
  labels:
    app.kubernetes.io/name: cloudfusion
    app.kubernetes.io/managed-by: kustomize
  name: ec2instance-sample
spec:
  # TODO(user): Add fields here
